version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Create a network and connect the app container to it
    networks:
      - devcontainer-network

  mongodb:
    image: mongo:8
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      # Connect using mongodb://root:example@mongodb:27017/

    # Add "forwardPorts": ["mongodb:27017"] to **devcontainer.json** to forward MongoDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    networks:
      - devcontainer-network

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/
      ME_CONFIG_BASICAUTH: false

    # Add "forwardPorts": ["mongo-express:8081"] to **devcontainer.json** to forward Mongo-express locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    networks:
      - devcontainer-network

  activemq:
    image: apache/activemq-classic:6.1.2
    restart: unless-stopped
    volumes:
      - activemq-data:/opt/apache-activemq/data
    environment:
      ACTIVEMQ_CONNECTION_USER: activemq
      ACTIVEMQ_CONNECTION_PASSWORD: activemq
      ACTIVEMQ_WEB_USER: admin
      ACTIVEMQ_WEB_PASSWORD: admin

    # Add "forwardPorts": ["activemq:8161"] to **devcontainer.json** to forward ActiveMQ Classic locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    networks:
      - devcontainer-network

networks:
  devcontainer-network:

volumes:
  mongodb-data:
  activemq-data:
